PabloElectricista/PF_Front

src/App.js, src/components/Card/index.jsx, src/components/CardContainer/index.jsx, src/views/ContactUs/index.jsx, src/views/CreateProduct/index.jsx, src/views/Home/index.jsx, src/views/LogIn/index.jsx, src/views/NotFound/index.jsx, src/views/Payment/index.jsx, src/views/ProductDetail/index.jsx, src/views/UserProfile/index.jsx
Creados las vistas/paginas de la app, y las rutas a cada una de estas en "app.js"
=> Creating view components

package-lock.json, package.json
installed bootstrap dependency for future use
=> Boostrap installed

src/App.js, src/index.js
Hi Team,
I fixed the App.js and store/indexjs files. Please review and comment.
=> App and store/index.js fixes

src/redux/actions/index.js, src/redux/reducer/index.js
Se creo la acción para traer todos los instrumentos y además se creo su actionType en el reducer
=> Creation action getAllIntruments

src/components/Card/Card.css, src/components/Card/index.jsx, src/components/CardContainer/CardContainer.css, src/components/CardContainer/index.jsx, src/components/Pagination/Pagination.css, src/components/Pagination/index.jsx, src/index.css, src/index.js
Las imágenes de prueba son demasiado pequeñas
Actualmente se ven pixeladas, pero es cuestión de comentar el "heigth:100%;" en .CardImg
=> Styles  card/card container/pagination

public/index.html, src/components/NavBar/index.jsx, src/views/LandingPage/index.css, src/views/LandingPage/index.jsx
Se modifico la landing page, se agrego un link al hmtl en la carpeta public y se volvio a cambiar el margin del navbar
=> Created landing page and somes changes

package-lock.json, package.json, src/components/Card/Card.css, src/components/Card/index.jsx, src/components/CardContainer/CardContainer.css, src/components/CardContainer/index.jsx, src/components/Filters/Filters.css, src/components/Filters/Filters.jsx
Se modificaron los estilos de las cards en el home y sus contenedores, se creo el componente filters, pero aun falta un funcionamiento, y por ultimo se instalo la dependencia de react-boostrap para fuera mas sencillo y rapido el estilizado
=> Styles changes

src/App.js, src/redux/actions/index.js, src/redux/reducer/index.js, src/views/ProductEdit/index.jsx
Hi Team,
The edit instrument was implemented.
=> Edit Instrument implementation

src/App.js, src/views/ProductDetail/index.jsx, src/views/ProductEdit/index.jsx
Hi Team,
The Edit and Details components were updated with the fields provided at the backend model.
Regards, Veronica.
=> Edit and Details model updates

src/components/Card/Card.css, src/components/Card/index.jsx, src/components/CardContainer/CardContainer.css, src/components/Filters/Filters.css, src/components/Filters/Filters.jsx, src/index.css, src/views/Home/index.css, src/views/Home/index.jsx
Se cambio el estilo del home y de sus cards para cambiar como se visualizaban con sus proporciones, ademas se cambio el color de fondo de la pagina en general, para que sea un poquitito mas gris
=> Change style in home with his components

src/components/Footer/Footer.css, src/components/Footer/index.jsx, src/components/NavBar/index.jsx, src/views/AboutUs/AboutUs.css, src/views/AboutUs/index.jsx, src/views/Carousel/Carousel.css, src/views/Carousel/index.jsx, src/views/Home/index.jsx, src/views/LandingPage/index.css, src/views/LandingPage/index.jsx
Se cambio el estilo del componente landing, se agregaron algunos componentes en ese mismo, se cambiaron ciertos estilos en el about us y se agrego la imagen de cada persona del equipo. por ultimo se cambiaron estilos en el navbar y el carousel
=> Changes landing

src/components/NavBar/index.jsx
Se agrego la funcionalidad del navbar, para que siempre este en la parte de arriba del navegador
=> min changes in navbar

src/components/NavBar/index.jsx, src/redux/actions/index.js, src/redux/reducer/index.js, src/views/ProductDetail/index.jsx, src/views/ProductEdit/index.jsx
Hi Team,
Please review and update. Note, the Edit and Details components were updated to use the getProductById action creator. Also, the image field was updated to img according to the backend product model. Also, the Favorites link was added to the NavBar.
=> Edit and Details - getProductById updates

src/redux/actions/index.js, src/redux/reducer/index.js, src/views/ProductDetail/index.jsx, src/views/ProductEdit/index.jsx
Hi Team,
The Edit and the Details components were connected to the backend. The instrument 'id' was changed to '_id' on all the related components. Note, that the categories and images were disabled on Edit component.
Regards, Veronica.
=> Edit and the Details components were connected to the backend

src/views/ProductDetail/ProductDetail.css, src/views/ProductEdit/ProductEdit.css, src/views/ProductEdit/index.jsx
Hi Team,
For your information, the Edit and Details styles were updated. Also, the ampersand symbol was added to Edit's regexAlphanumeric variable.
Regards, Veronica.
=> Edit and Details CSS updates

src/components/CardContainer/index.jsx, src/components/Footer/Footer.css, src/components/Footer/index.jsx, src/components/NavBar/NavBar.css, src/components/NavBar/index.jsx, src/customScripts.js, src/views/AboutUs/index.jsx, src/views/Carousel/index.jsx, src/views/Home/index.jsx, src/views/LandingPage/index.css, src/views/LandingPage/index.jsx
Se creo el archivo custom scripts, donde esta el codigo para subir a la parte superior de la pantalla.
Se agrego el use effect de subir en la parte de arriba de la pantalla cada vez que se cambia de pagina
Se cambio el diseño del footer.
Se cambio los colores del navbar.
Se corrigio el nombre de Roger en about us.
se cambio los colores de los botones del carousel.
=> Various changes in styles

src/components/CardContainer/CardContainer.css, src/components/CardContainer/index.jsx
Se creo el boton despleglable con sus estilos
=> Dropdown button

src/views/ProductDetail/index.jsx, src/views/ProductEdit/ProductEdit.css, src/views/ProductEdit/index.jsx
=> Edit and Details updates for categories

src/components/SearchBar/index.jsx, src/views/CreateProduct/index.jsx
con este mínimo cambio se redirecciona la searchbar desde cualquier punto, necesita un leve ajuste en estilo(David)
=> [redirection of searchBar]

src/views/ProductDetail/ProductDetail.css, src/views/ProductDetail/index.jsx, src/views/ProductEdit/ProductEdit.css, src/views/ProductEdit/index.jsx
Hi Team,
Please approve.
1. Add and remove image buttons:
2. All the product images are displayed:
=> The Edit and Details image code was updated to handle the image array

src/App.js, src/components/Card/Card.css, src/components/Card/index.jsx, src/components/CardContainer/CardContainer.css, src/components/CardContainer/index.jsx, src/components/Filters/Filters.css, src/components/Filters/Filters.jsx, src/components/Footer/Footer.css, src/components/History/History.css, src/components/History/History.jsx, src/components/NavBar/NavBar.css, src/components/NavBar/index.jsx, src/components/SearchBar/SearchBar.css, src/components/SearchBar/index.jsx, src/index.css, src/views/AboutUs/AboutUs.css, src/views/Carousel/Carousel.css
Se agrego el componente history.
Ahora el footer este donde este siempre estará en el fondo.
Se ajustaron y añadieron estilos a las card (Rating en estrellas, strike de los botones, etc).
Se agregaron animaciones al carrusel y al componente de filtros.
Se quito la ventana de favoritos para posteriormente colocarla en un dropdown del perfil.
Se hizo un cambio mínimo en el funcionamiento del searchBar.
=> Styles and functional changes

src/views/ProductDetail/ProductDetail.css, src/views/ProductDetail/index.jsx
=> Details images were updated with Carousel

src/components/CardContainer/index.jsx, src/redux/reducer/index.js, src/views/CreateProduct/index.jsx
implentacion de cambios en el form, aun quedan varias modificaciones, en especial cuando se requiera usuario, la ruta de cloudinary esta en proceso de conexion con el back
=> [Attempt/Form for pre-demo]

package-lock.json, package.json, src/components/Card/Card.css, src/components/CardContainer/CardContainer.css, src/components/CardContainer/index.jsx, src/components/Filters/Filters.css, src/components/NavBar/NavBar.css, src/index.css, src/redux/actions/index.js, src/redux/reducer/index.js, src/views/AboutUs/AboutUs.css, src/views/AboutUs/index.jsx, src/views/LandingPage/index.css
Se instalo Material UI, recordar hacer npm i.
Se cambio la fuente de la pagina en general y el log tiene una fuente única.
Se agregaron animación en las cards y en el filter.
El ordenamiento se paso a un select.
Se Modifico cierta parte de las acciones de ordenamiento, ahora es una sola.
=> Order inButton and styles changes

src/components/Loading/Loading.css, src/components/Loading/Loading.jsx, src/components/NothingFound/NothingFound.css, src/components/NothingFound/NothingFound.jsx, src/index.css, src/redux/actions/index.js, src/redux/reducer/index.js, src/views/Home/Home.css, src/views/Home/Home.jsx
Se modifico el componente de loading.
Ahora el loading aparece antes de mostrar cada producto, se agrego una accion para activarlo y en cada acción que traia productos del back, se le agrego una parte para que lo desactive.
Se agrego el component de Not found que aparece cuando no hay productos.
Tambien se agrego un contador de resultado.
=> Changes in loading component and creation of nothing found component

src/App.js, src/components/Alerts/AlertMessage.jsx, src/components/Modal/ModalVerification.jsx, src/redux/actions/index.js, src/redux/reducer/index.js, src/views/ProductDetail/ProductDetail.jsx, src/views/ProductEdit/ProductEdit.jsx
=> The ModalVerification and the AlertMessage were added

src/views/ProductEdit/ProductEdit.css, src/views/ProductEdit/ProductEdit.jsx
=> The Edit's status field was changed to radio buttons. Also, the CSS was updated.

src/redux/actions/index.js, src/views/ContactUs/index.jsx, src/views/CreateProduct/index.jsx
Con este ultimo cambio, el contact us recibe el reclamo desde la pagina y se envia una respuesta automatica al correo de quien hizo el reclamo, ademas del reclamo a la oficina de bgoode.
=> contact changes/ funcionando

src/App.js, src/views/Home/Home.jsx, src/views/ProductDetail/ProductDetail.css, src/views/ProductDetail/ProductDetail.jsx
=> ProductDetail component was updated with the add to favorites and add to cart buttons

src/components/Card/Card.jsx, src/components/Footer/Footer.css, src/components/Footer/Footer.jsx, src/components/ReviewForm/ReviewForm.css, src/components/ReviewForm/ReviewForm.jsx, src/components/ReviewList/ReviewList.css, src/components/ReviewList/ReviewList.jsx, src/views/ProductDetail/ProductDetail.css, src/views/ProductDetail/ProductDetail.jsx
Se termino el formulario para elegir la cantidad del producto y poder proceder con el pago, se agrego estilos al form de review
Se quitaron los skeleton
=> Forms detail

src/components/ShoppingCart/ShopCard.jsx, src/components/ShoppingCart/index.jsx, src/views/ProductDetail/ProductDetail.jsx
=> The Product's quantity was configured to display the same updated value

src/components/NothingFound/NothingFound.css, src/components/SearchBar/SearchBar.jsx, src/components/ShoppingCart/Card.css, src/components/ShoppingCart/index.jsx
Se modifico el estilo del formulario de pago, tambien se cambio la logica del search bar que estaba fallando y se arreglo el ancho de la carta cuando se busca un producto que no existe
=> Styles payment
